FROM {{ image_base }}

{% for user_lib in user_baselibs %}
ADD .user-baselibs/{{ user_lib }} /app/{{ user_lib }}
RUN cd /app/{{ user_lib }} && test -f requirements.txt && pip3 install -r requirements.txt || echo "no reqs for {{ user_lib }}"
{% endfor %}

RUN pip install google-events==0.11.0

{% for source in sources %}
ADD {{ source.origin }} {{ source.destination }}
{% endfor %}

