apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVTmF1L3dpei9Tbk5FY1dzdStqa0pKOFpCTFQ4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRGN4TURBNE5ERXlOMW9YRFRNegpNRGN3TnpBNE5ERXlOMW93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4SERvcXdzeDdOZVhFd3dOM1AzSHlNUmVGdWhWaFdVRGNtR1AKQ0M3UkFkUlV4QlJjQVoyS1JoMjlQcDNodFdrYk1nOEJ3UThQNzZBOWtRU0xKZWFzZFI5UWtUazAvMDZDbXhFSQo5OXFMYkhiZzN1Um1NTEJJVHlCOFlnNFF0NVFOdCtwVjNUMzFIcXVpa0EvamxvaGcyODAvOEZxa1ZwQ2VjSjd0ClJpdElKMjRMT3IrZG0xSlY4SUpHOVowVTdtc3FOZFcwcGF6cituTUxnNmFMU1NwNWJDNnpnZG5VdjVYaGh1WmgKUSt6R3d2Qm03Szk0TFRwTlNId2kwNnZqc3lXckRBQ2JQMlNIZ3l2bUpqeElyWGhCUER0R1pXRmc5RTh3RG16TAp3R0xTZ3FlWkpMeEt4ZVRvaXovRyswOVdNL2UyRWkyektvN2U1WHhySXgyRWVnWlcwUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVWg5alBzSEN5dTU2WEdMRjNlYnV2WFpPVUx0Z3dId1lEVlIwakJCZ3dGb0FVaDlqUHNIQ3kKdTU2WEdMRjNlYnV2WFpPVUx0Z3dEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBbmpVQjhYSGNyS0RaSzBMUGhJd2lxcTMwb3lIOUt2ZXNWMUgwZmdqdXVSc3RCT3NkcnFZREVDenJlOTk1ClFXSDBQcjZDUyt5U1VNZzNnTkc0MFMzeklsb0RLdzRET0ZPSURkYkJZbzNrSnRZbk1XSm9zL1dhczVaK0lqNW0KZzlXcTA5TFVFUTJlNVdBbGJZY21sMHJ3N1VHcWplUGg1MlZ0cnRTQlBmWUZIVm5PdTRJYUp1RXJlNEhUZzhtWQpQMFpqSktSMTRDbHlvN3kvN0dOaWUvNTdhVkU3YitZS1ZyTFlQeUFFbldUR1k1Q1ErajJvdXhXUTBKL0lZM3pyCm1pb2JXN09BZkYzNDREeWEzZWZiaG8zaGQwTGM5cVI4d2s4b001U0RZQXVjWEEvTGJnUnBMNG5FbFp4a0hJMjQKRU5teksreC9yRGpuSWMwdS9OS20yUnFWUUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: S0hvN0ZCa2hMYUowZjM2WjV1anluUkVQdStqUVpET2k2VXU3VzMvbllVQT0K
