FROM {{ image_base}}

{% for user_lib in user_baselibs %}
ADD .user-baselibs/{{ user_lib }} /app/{{ user_lib }}
RUN cd /app/{{ user_lib }} && test -f requirements.txt && pip3 install -r requirements.txt || echo "no reqs for {{ user_lib }}"
{% endfor %}

{% for source in sources %}
ADD {{ source.origin }} {{ source.destination }}
{% endfor %}

RUN pip install --no-cache-dir fastapi==0.92.0 redis==3.5.3 uvicorn[standard]==0.17.6

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
